### ISSUE TITLE
OpenAPI 3.1

### ISSUE THREAD

**Issue by atollk** [cjbooms/fabrikt#140]
The most recent OpenAPI standard is version 3.1. Fabrikt currently uses [KaiZen-OpenApi-Parser](https://github.com/RepreZen/KaiZen-OpenApi-Parser), which only supports 3.0 and is unlikely to be updated further, since the last commit on that project happened three years ago. 

It would be nice if Fabrikt could support OpenAPI 3.1 as well, using something like [swagger-parser](https://github.com/swagger-api/swagger-parser) instead.

**Comment by cjbooms** [comment]
I was thinking it might be easier to just pull all of the code from kaizen directly into the fabrikt code base and update it with support for 3.1. 

I'll take a look at that other parser though. Thanks

**Comment by rajki** [comment]
On the topic of OpenAPI 3.1, is there an interest in supporting the newly introduced webhooks section @cjbooms? Perhaps it warrants a separate discussion.

Reference: https://spec.openapis.org/oas/v3.1.0#oasWebhooks
Example implementation: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml

**Comment by cjbooms** [comment]
I have added a test that validates the the example OpenApi 3.1 schema you linked above does generate models correctly in [this PR](https://github.com/cjbooms/fabrikt/pull/155/files).

I think that a separate issue for adding support for webhooks is a good idea. If we take that approach we can look at adding 3.1 features incrementally as users request them. 
I do not have any experience authoring webhooks, so I would need you to provide the code examples you would expect Fabrikt to generated for a given input API.

**Comment by rajki** [comment]
Thanks for the quick response, @cjbooms! Glad to see the model generation validation passing for v3.1. 

On the topic of webhooks, the controller generation itself is straightforward and should be possible to do with the existing functionality. This is due to the fact that the webhooks section of an OpenAPI 3.1 spec is nothing but a map of labels to Path Item objects.

Now, the one catch here is that there is open ended scope for value of the request mapping. So, IMO Fabrikt as a library has to make an opinionated call on defaults (eg., `/webhooks/<label>`) and consider exposing an extension to customise the path.

Wdyt?

**Comment by cjbooms** [comment]
Closing this as we have validated that 3.1 is supported, but there are some feature gaps. Individual 3.1 features can be requested in dedicated issues as needed
