### ISSUE TITLE
Still problem with norwegian letters

### ISSUE THREAD

**Issue by alpet** [cjbooms/fabrikt#170]
Hi the previous fix partialy mitigated the problem. The Enums started to work and also property names with norwegian letters also started to generated. Unfortunaly I have a problem now with the classes. Here is a sample of what works and what does not work:

THIS DO NOT WORK  (is not generated at all)
ÅrsakInnsending:
      type: object
      properties:
        test:
          type: string
          
  THIS WORKS:
  
  ÅrsakInnsending:
      type: string
      enum:
        - Ny
        - Endring

**Comment by cjbooms** [comment]
Bad news, the parser used by fabrkit [will not permit these characters](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/master/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/types3.yaml#L61-L64) in schema object names. 

This is because they are not valid for schema names according to the [OpenApi3 specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#components-object):
```
All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.
```

**Comment by alpet** [comment]
Thanks :) I will survive the missing charset :) Still the previous change was good because it enabled the fields to have non ascii characters. So now the json can have them.
